version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: subscriptions-postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-subscriptions}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-subscriptions}"]
      interval: 3s
      timeout: 3s
      retries: 30
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate:v4.17.0
    depends_on:
      postgres:
        condition: service_healthy
    command: [
      "-path", "/migrations",
      "-database", "postgres://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@postgres:5432/${DB_NAME:-subscriptions}?sslmode=disable",
      "up"
    ]
    volumes:
      - ./migrations:/migrations:ro
    restart: "no"

  app:
    build: .
    image: subscriptions-app:latest
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    env_file:
      - .env
    ports:
      - "${SERVER_PORT:-8080}:8080"

volumes:
  pgdata: {}
