basePath: /
definitions:
  models.CreateSubscriptionRequest:
    properties:
      end_date:
        example: 09-2025
        type: string
      price:
        example: 500
        type: integer
      service_name:
        example: Test Service
        type: string
      start_date:
        example: 07-2025
        type: string
      user_id:
        example: 60601fee-2bf1-4721-ae6f-7636e79a0cba
        type: string
    type: object
  models.SubscriptionResponse:
    properties:
      end_date:
        example: 09-2025
        type: string
      id:
        example: b548150d-6198-4cc1-a186-8c4a1e0ccdcf
        type: string
      price:
        example: 500
        type: integer
      service_name:
        example: Test Service
        type: string
      start_date:
        example: 07-2025
        type: string
      user_id:
        example: 60601fee-2bf1-4721-ae6f-7636e79a0cba
        type: string
    type: object
  models.TotalCostResponse:
    properties:
      total:
        type: integer
    type: object
  models.UpdateSubscriptionRequest:
    properties:
      end_date:
        description: '"" — очистить конец'
        example: ""
        type: string
      price:
        example: 450
        type: integer
      service_name:
        example: Yandex Plus
        type: string
      start_date:
        example: 08-2025
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: Subscriptions API
  description: REST-сервис для управления онлайн-подписками пользователей.
  title: Subscriptions API (Swagger)
  version: "1.0"
paths:
  /api/subscriptions:
    get:
      description: Список подписок с фильтрами и пагинацией
      parameters:
      - description: Filter by user UUID
        example: '"b548150d-6198-4cc1-a186-8c4a1e0ccdcf"'
        in: query
        name: user_id
        type: string
      - default: '"Test Service"'
        description: Filter by service name
        example: '"Test Service"'
        in: query
        name: service_name
        type: string
      - default: 20
        description: Page size (default 20, max 100)
        example: 20
        in: query
        name: limit
        type: integer
      - default: 0
        description: Offset (default 0)
        example: 0
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.SubscriptionResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: List subscriptions
      tags:
      - subscriptions
    post:
      consumes:
      - application/json
      description: Создаёт запись о подписке
      parameters:
      - description: Subscription body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.CreateSubscriptionRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.SubscriptionResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create subscription
      tags:
      - subscriptions
  /api/subscriptions/{id}:
    delete:
      description: Удаляет подписку по её ID
      parameters:
      - description: Subscription ID (UUID)
        example: '"b548150d-6198-4cc1-a186-8c4a1e0ccdcf"'
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete subscription by id
      tags:
      - subscriptions
    get:
      description: Возвращает запись по её ID
      parameters:
      - description: Subscription ID (UUID)
        example: '"b548150d-6198-4cc1-a186-8c4a1e0ccdcf"'
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SubscriptionResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get subscription by id
      tags:
      - subscriptions
    patch:
      consumes:
      - application/json
      description: Частичное обновление полей подписки. Чтобы очистить end_date, передайте
        "".
      parameters:
      - description: Subscription ID
        example: '"b548150d-6198-4cc1-a186-8c4a1e0ccdcf"'
        format: uuid
        in: path
        name: id
        required: true
        type: string
      - description: Fields to update
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.UpdateSubscriptionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SubscriptionResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Patch subscription
      tags:
      - subscriptions
  /api/subscriptions/total:
    get:
      description: 'Суммарная стоимость подписок за период [from; to] в месяцах. Формат
        дат: MM-YYYY.'
      parameters:
      - description: From month (MM-YYYY)
        example: '"07-2025"'
        in: query
        name: from
        required: true
        type: string
      - description: To month (MM-YYYY)
        example: '"09-2025"'
        in: query
        name: to
        required: true
        type: string
      - description: Filter by user UUID
        example: '"60601fee-2bf1-4721-ae6f-7636e79a0cba"'
        format: uuid
        in: query
        name: user_id
        type: string
      - description: Filter by service name
        example: '"Yandex Plus"'
        in: query
        name: service_name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TotalCostResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Total cost for a period
      tags:
      - subscriptions
schemes:
- http
swagger: "2.0"
